### ISSUE TITLE
1.7.10-1.5 Duplicate Stat ID Crash

### ISSUE THREAD

**Issue by sdaddy** [gildedgames/aether-issues#543]
Crash report: http://pastebin.com/iFaSJFKU

**Comment by MrKrabat** [comment]
I've got the same, in my case it occurs with EnderZoo
http://pastebin.com/60GbQgXk

**Comment by sdaddy** [comment]
This is third one I've seen. Someone posted on Minecraft Forum about the Foliaath from Mowzie's Mobs.

**Comment by Collin1971** [comment]
Marking this issue as a bug since it affects multiple people.

Does this issue only exist in 1.7.10-1.5, or previous versions as well?

**Comment by sdaddy** [comment]
I didn't have this issue in the previous version.

**Comment by MrKrabat** [comment]
with 1.7.10-1.4 it works

**Comment by Amaxter** [comment]
Can confirm as well: http://hastebin.com/ijavinotek.coffee (With YGC)

**Comment by Collin1971** [comment]
There's a pretty serious bug with something we implemented in the last update. Essentially, every mod that adds a spawn egg will _probably_ crash when installed side by side with the Aether.

We're looking into fixing it ASAP.

**Comment by Collin1971** [comment]
We've found the culprit and have patched it in 1.7.10-1.5.1. We'll be releasing a very small bug-fix update within the next few days to address this and other critical issues.

**Comment by Amaxter** [comment]
Good to hear!

**Comment by Collin1971** [comment]
Heyo, we want to double check that we've resolved this issue in the next version.

If you were having stat ID issues, please try this build and report back if it works.

http://files.aetherii.com/files/versions/custom/aether-1.7.10-1.5.1-543fix.jar

**Comment by MrKrabat** [comment]
the game is loading but there is still a problem with Aether II spawn eggs

NEI can't find aether spawn eggs and when opening the creative "Aether Miscellaneous" Tab the game crash.
https://gist.github.com/MrKrabat/1a417cd4cb47f3daa69d

but EnderZoo works fine

**Comment by Collin1971** [comment]
grr, we had some generic casting and I didn't notice. Does this build fix the issues you described?

http://files.aetherii.com/files/versions/custom/aether-1.7.10-1.5.1-543fix-2.jar

**Comment by MrKrabat** [comment]
yes, this build fix the problems :)

EnderZoo works well

**Comment by Collin1971** [comment]
We've released an update to address the issue.

http://files.aetherii.com/files/versions/1.7.10-1.5.1/aether-1.7.10-1.5.1.jar
